name: Flask CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8

    # Format code with black
    - name: Format code with black
      run: black --check .

    # Run flake8 linting
    - name: Lint with flake8
      run: flake8 .

    # Run tests
    - name: Run tests
      run: |
        pytest

    # Deploy to Render
    - name: Deploy to Render
      if: github.ref == 'refs/heads/main' && success()
      env:
        RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
      run: |
        curl -X POST $RENDER_DEPLOY_HOOK
