name: Flask CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        py-version: 3.9

    # Install dependencies
    - name: Install dependencies
      run: |
        py -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run linting
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    # Run tests
    - name: Run tests
      run: |
        pip install pytest
        pytest

    # Deploy to Render
    - name: Deploy to Render
      if: github.ref == 'refs/heads/main' && success()
      env:
        RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
      run: |
        curl -X POST $RENDER_DEPLOY_HOOK
